### ISSUE TITLE
Received empty url after moss ran for 10 minutes

### ISSUE THREAD

**Issue by robert1003** [soachishti/moss.py#33]
As the title says, when I sent about 150 cpp in a submission,
the error prompts after doing nothing for about 10 minutes.
I'm pretty sure that my userid is correct, and I can reach moss.standford.edu:7690
(I tested with `nc -v -u -z -w 30 moss.stanford.edu 7690` : `Connection to moss.stanford.edu 7690 port [udp/*] succeeded!`)

I've tried quite a few times yesterday and today and it's still not working.
Any idea why this is happening?

**Comment by soachishti** [comment]
For record citing from Moss website (https://theory.stanford.edu/~aiken/moss/).

`April 10, 2020, The dramatic increase in online courses due to the coronavirus pandemic seems to have led to a corresponding dramatic increase in the use of Moss over the last few weeks. (It's not clear why these two things should be related, but it appears they are.) The public server has been moved to a larger machine (more cores and more memory), which should help meet the increased demand. Difficulties connecting to the server or receiving results are a sign that the server is overloaded at that time; please try again later. All users are asked to limit submissions to no more than 100/day.`

closing this issue.
